//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.12 at 10:14:00 AM BST 
//


package developer.betfair.generator;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}request"/>
 *         &lt;element ref="{}simpleResponse"/>
 *         &lt;element ref="{}exceptions"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "request",
    "simpleResponse",
    "exceptions"
})
@XmlRootElement(name = "parameters")
public class Parameters {

    @XmlElement(required = true)
    protected Request request;
    @XmlElement(required = true)
    protected SimpleResponse simpleResponse;
    @XmlElement(required = true)
    protected Exceptions exceptions;

    /**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     {@link Request }
     *     
     */
    public Request getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     {@link Request }
     *     
     */
    public void setRequest(Request value) {
        this.request = value;
    }

    /**
     * Gets the value of the simpleResponse property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleResponse }
     *     
     */
    public SimpleResponse getSimpleResponse() {
        return simpleResponse;
    }

    /**
     * Sets the value of the simpleResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleResponse }
     *     
     */
    public void setSimpleResponse(SimpleResponse value) {
        this.simpleResponse = value;
    }

    /**
     * Gets the value of the exceptions property.
     * 
     * @return
     *     possible object is
     *     {@link Exceptions }
     *     
     */
    public Exceptions getExceptions() {
        return exceptions;
    }

    /**
     * Sets the value of the exceptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Exceptions }
     *     
     */
    public void setExceptions(Exceptions value) {
        this.exceptions = value;
    }

}
